version: '3.4'

services:
  berlinclock:
    image: berlinclock
    container_name: berlinclock
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9080:9080

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    build:
      context: .
      dockerfile: ./Dockerfile-swagger
    ports:
      - 8080:8080
